version: "3.7"

services:
  flask:
    build: ./labos
    container_name: flask13
    restart: always
    expose:
      - 8080
    networks:
      my-network:
        aliases:
          - flask-app 
  
  nginx:
    build: ./nginx
    container_name: nginx13
    restart: always
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - flask
networks:
  my-network: {}
